before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: ttff-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/k1LoW/ttff.version={{.Version}} -X github.com/k1LoW/ttff.commit={{.FullCommit}} -X github.com/k1LoW/ttff.date={{.Date}} -X github.com/k1LoW/ttff/version.Version={{.Version}}
-
  id: ttff-darwin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  ldflags:
    - -s -w -X github.com/k1LoW/ttff.version={{.Version}} -X github.com/k1LoW/ttff.commit={{.FullCommit}} -X github.com/k1LoW/ttff.date={{.Date}} -X github.com/k1LoW/ttff/version.Version={{.Version}}
archives:
-
  id: ttff-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: ttff
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/ttff
  description: ttff is a tool for TrueType Font Files
